apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
  labels:
    app: example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example # this should match the selector in service.yml
  template:
    metadata:
      labels:
        app: example # this should match the selector in service.yml
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: example
          image: ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ "ALL" ]
            seccompProfile:
              type: RuntimeDefault
          ports:
            - containerPort: 8080

