name: brakeman
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: brakeman
        uses: artplan1/brakeman-action@v1.2.1
        with:
          flags: "--color"