name: workflow for Maven using Snyk security scan
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle-jdk17@v4
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}