name: workflow for Maven using Snyk security scan
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest
    env:
      MY_GITHUB_ACTOR: ${{ secrets.MY_GITHUB_ACTOR }}
      MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - run: |
          echo ${{ github.workspace }}
          echo $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE
          ls

#      - name: Run Snyk to check for vulnerabilities
#        uses: snyk/actions/maven-3-jdk-21@master
#        continue-on-error: true
#
#      - name: Run Snyk code test
#        uses: snyk/actions/maven-3-jdk-21@master
#        continue-on-error: true
#        with:
#          command: code test
#
#      - name: Snyk Infrastructure-as-Code Scanning
#        uses: snyk/actions/maven-3-jdk-21@master
#        continue-on-error: true
#        with:
#          command: iac test

