name: workflow for Maven using Snyk security scan
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
      - uses: snyk/actions/maven@master
        continue-on-error: true
        env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}